### PR TITLE
switch to dune

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

I just switched the project to dune.

Cheers.

### CODE REVIEW

**Comment by redianthus** [comment]
@lefessan could you have a look at this PR ? It's clearer if you look only at the first commit. The second one is just a formatting pass. I would like to publish optal to opam.

**Comment by lefessan** [comment]
First commit: why not use `drom` to create the project ? it would be a good exercise to test it, no ?
Second commit: I am not fond of the result of calling `ocamlformat`. It's definitively a decision to be taken by the main author, Pierre Chambart in this case.

**Comment by redianthus** [comment]
Because I did this in 2019. (:

I'll remove the 2nd comit then.

**Comment by redianthus** [comment]
@lefessan ping. :)

**Comment by lefessan** [comment]
I think we should keep a `Makefile` with rules `all` and `depends`, since `optal` should at least install some opam packages (`opam install menhir jsonm`).

**Comment by redianthus** [comment]
@lefessan, done in the last commit

**Comment by redianthus** [comment]
@lefessan thanks ! Could you give me write access to the repository so I can make an opam release ? (I need to push a new git tag etc.)

**Pull request merged**
